// <auto-generated />
using GreenThumb.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenThumb.Migrations
{
    [DbContext(typeof(GreenThumbDbContext))]
    [Migration("20231206212856_Final-Version1.0")]
    partial class FinalVersion10
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GreenThumb.Models.GardenModel", b =>
                {
                    b.Property<int>("GardenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GardenId"), 1L, 1);

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("GardenId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Gardens");
                });

            modelBuilder.Entity("GreenThumb.Models.GardenPlant", b =>
                {
                    b.Property<int>("GardenId")
                        .HasColumnType("int")
                        .HasColumnName("garden_id");

                    b.Property<int>("PlantId")
                        .HasColumnType("int")
                        .HasColumnName("plant_id");

                    b.Property<int>("Quanity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("GardenId", "PlantId");

                    b.HasIndex("PlantId");

                    b.ToTable("GardenPlant");
                });

            modelBuilder.Entity("GreenThumb.Models.InstructionModel", b =>
                {
                    b.Property<int>("InstructionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructionId"), 1L, 1);

                    b.Property<string>("InstructionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("instruction_text");

                    b.Property<int>("PlantId")
                        .HasColumnType("int")
                        .HasColumnName("plant_id");

                    b.HasKey("InstructionId");

                    b.HasIndex("PlantId");

                    b.ToTable("Instructions");

                    b.HasData(
                        new
                        {
                            InstructionId = 1,
                            InstructionText = "6 hours of sunlight per day",
                            PlantId = 1
                        },
                        new
                        {
                            InstructionId = 2,
                            InstructionText = "Water in the morning",
                            PlantId = 1
                        },
                        new
                        {
                            InstructionId = 3,
                            InstructionText = "Remove dead leaves",
                            PlantId = 1
                        },
                        new
                        {
                            InstructionId = 4,
                            InstructionText = "Fertilize during spring or early summer",
                            PlantId = 1
                        },
                        new
                        {
                            InstructionId = 5,
                            InstructionText = "Inspect regularly for pests",
                            PlantId = 1
                        },
                        new
                        {
                            InstructionId = 6,
                            InstructionText = "6 hours of sunlight per day",
                            PlantId = 2
                        },
                        new
                        {
                            InstructionId = 7,
                            InstructionText = "Good drainage to prevent root rot",
                            PlantId = 2
                        },
                        new
                        {
                            InstructionId = 8,
                            InstructionText = "Water when soil is dry on touch",
                            PlantId = 2
                        },
                        new
                        {
                            InstructionId = 9,
                            InstructionText = "Remove bad blooms",
                            PlantId = 2
                        },
                        new
                        {
                            InstructionId = 10,
                            InstructionText = "Harvest leaves when young for culinary use",
                            PlantId = 2
                        },
                        new
                        {
                            InstructionId = 11,
                            InstructionText = "At least 6 hours of sunlight per day",
                            PlantId = 3
                        },
                        new
                        {
                            InstructionId = 12,
                            InstructionText = "Mix sand into soil for better drainage",
                            PlantId = 3
                        },
                        new
                        {
                            InstructionId = 13,
                            InstructionText = "Dry soil completely between watering",
                            PlantId = 3
                        },
                        new
                        {
                            InstructionId = 14,
                            InstructionText = "Protect from colder than 10C",
                            PlantId = 3
                        },
                        new
                        {
                            InstructionId = 15,
                            InstructionText = "Repot every 2-3 years if you want growth",
                            PlantId = 3
                        },
                        new
                        {
                            InstructionId = 16,
                            InstructionText = "Plant with full sunlight and slightly acidic to neutral soil",
                            PlantId = 4
                        },
                        new
                        {
                            InstructionId = 17,
                            InstructionText = "Consistent and deep watering",
                            PlantId = 4
                        },
                        new
                        {
                            InstructionId = 18,
                            InstructionText = "Regular pruning, especially in late winter / early spring",
                            PlantId = 4
                        },
                        new
                        {
                            InstructionId = 19,
                            InstructionText = "Fertilize annually in early spring",
                            PlantId = 4
                        },
                        new
                        {
                            InstructionId = 20,
                            InstructionText = "Monitor regularly for signs of pests",
                            PlantId = 4
                        },
                        new
                        {
                            InstructionId = 21,
                            InstructionText = "Plant in a well-drained and sunny spot",
                            PlantId = 5
                        },
                        new
                        {
                            InstructionId = 22,
                            InstructionText = "Consistent watering, water at the base",
                            PlantId = 5
                        },
                        new
                        {
                            InstructionId = 23,
                            InstructionText = "Install stakes to provide support while growing",
                            PlantId = 5
                        },
                        new
                        {
                            InstructionId = 24,
                            InstructionText = "Remove bad blooms directly",
                            PlantId = 5
                        },
                        new
                        {
                            InstructionId = 25,
                            InstructionText = "Use a slow fertilizer in early spring",
                            PlantId = 5
                        });
                });

            modelBuilder.Entity("GreenThumb.Models.PlantModel", b =>
                {
                    b.Property<int>("PlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlantId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("img_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("PlantId");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            PlantId = 1,
                            Description = "The rose is a perennial flowering plant known for its exquisite and diverse beauty. With its lush, fragrant blossoms and thorny stems, the rose has become a symbol of love, passion, and elegance. The flower's intricate layers of petals form a captivating array of colors, ranging from classic reds and pinks to whites, yellows, and even blues. Roses are cultivated in various varieties, each showcasing unique shapes and sizes. Beyond its aesthetic appeal, the rose has cultural and symbolic significance in art, literature, and traditions worldwide.",
                            ImgUrl = "https://images.photowall.com/products/59359/red-rose.jpg?h=699&q=85",
                            Name = "Rose"
                        },
                        new
                        {
                            PlantId = 2,
                            Description = "The dandelion (Taraxacum officinale) is a common flowering plant known for its distinctive yellow flowers that transform into fluffy seed heads resembling small parachutes. Despite being considered a weed in many lawns, dandelions have notable health benefits and culinary uses. The plant's leaves, flowers, and roots are all utilized in various traditional and alternative medicines.",
                            ImgUrl = "https://wildflower-favours.co.uk/wp-content/uploads/2022/04/dandelion.jpg",
                            Name = "Dandelion"
                        },
                        new
                        {
                            PlantId = 3,
                            Description = "Cacti are a unique group of succulent plants known for their distinctive appearance, typically characterized by thick, fleshy stems and spines. Adapted to arid environments, cacti are renowned for their water storage capabilities, enabling them to survive in dry and challenging conditions. They come in various shapes and sizes, ranging from the iconic saguaro cactus with arms to small, globular species.",
                            ImgUrl = "https://www.lovethegarden.com/sites/default/files/styles/large/public/content/articles/UK_plant-finder-indoor-plants-saguaro-cactus_main.jpg?itok=qCFCzXFH",
                            Name = "Cactus"
                        },
                        new
                        {
                            PlantId = 4,
                            Description = "The pear tree (Pyrus) is a deciduous fruit tree known for producing the sweet and succulent pear fruit. With a graceful and spreading canopy, the pear tree typically features simple, ovate leaves that provide a vibrant green backdrop during the growing season. In spring, the tree showcases clusters of white to pinkish blossoms, contributing to its ornamental appeal. Pears, the tree's fruit, vary in shape, size, and color, with popular varieties including Bartlett, Bosc, and Anjou. The fruit ripens in late summer to early fall, offering a juicy and flavorful treat enjoyed fresh or used in various culinary applications, from desserts to preserves. Pear trees are valued not only for their delicious fruit but also for their aesthetic contributions to gardens and orchards, providing shade and visual interest throughout the seasons.",
                            ImgUrl = "https://th.bing.com/th/id/OIG.gpxPEeeHCxn5.h_rIBId?pid=ImgGn",
                            Name = "Pear Tree"
                        },
                        new
                        {
                            PlantId = 5,
                            Description = "The peony (Paeonia) is a prized perennial known for its large, fragrant blooms with layered petals in various colors. Blooming in late spring to early summer, these luxurious flowers, set against glossy green foliage, add elegance to gardens and floral arrangements. Symbolizing love and prosperity, peonies are cherished for their enduring beauty and adaptability to well-drained soils.",
                            ImgUrl = "https://th.bing.com/th/id/OIG.j3RcQJt8GSbQNJWIj3en?pid=ImgGn",
                            Name = "Peony"
                        });
                });

            modelBuilder.Entity("GreenThumb.Models.UserModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GreenThumb.Models.GardenModel", b =>
                {
                    b.HasOne("GreenThumb.Models.UserModel", "User")
                        .WithOne("Garden")
                        .HasForeignKey("GreenThumb.Models.GardenModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenThumb.Models.GardenPlant", b =>
                {
                    b.HasOne("GreenThumb.Models.GardenModel", "Garden")
                        .WithMany()
                        .HasForeignKey("GardenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenThumb.Models.PlantModel", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Garden");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("GreenThumb.Models.InstructionModel", b =>
                {
                    b.HasOne("GreenThumb.Models.PlantModel", "Plant")
                        .WithMany("Instructions")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("GreenThumb.Models.PlantModel", b =>
                {
                    b.Navigation("Instructions");
                });

            modelBuilder.Entity("GreenThumb.Models.UserModel", b =>
                {
                    b.Navigation("Garden")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
